-- Lisää DROP TABLE lauseet tähän tiedostoon 
DROP TABLE IF EXISTS Sopimus CASCADE;
DROP TABLE IF EXISTS Tilasto CASCADE;
DROP TABLE IF EXISTS Pelaaja CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Joukkue CASCADE;